theme: jekyll-theme-slate
title: Hannah E. Burson

description: Combinatorial Number Theorist
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:  #if your site has a twitter account, enter it here

# Author Settings
author: Hannah E. Burson # add your name
author-img: heburson_photo.png # add your photo
about-author: "Number Theorist | Researcher | Educator."  # add description
social-twitter: 
social-facebook: # add your Facebook handle 
social-github: 
social-linkedin: hannah-burson-73295a43 # add your Linkedin handle
social-email: hburso2@illinois.edu # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
 analytics: UA-165016758-1

# Build Settings
markdown: kramdown
#plugins:
#  - jekyll-sitemap
#  - jekyll-paginate
#  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
