theme: jekyll-theme-slate
title: Hannah E. Burson, PhD
description: Combinatorial number theorist.

#Author settings
author: Hannah E. Burson, PhD # add your name
author-img: photo.png
social-email: hburson@umn.edu

show_downloads: false
is_project_page: false
google_analytics: UA-165016758-1
theme: jekyll-theme-slate
